### ISSUE TITLE
UUID Issue

### ISSUE THREAD

**Issue by dkaplan88** [enova/landable#32]
One app is having trouble installing the Landable Migrations and is getting the error 

```
PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts
```

This error is especially strange as `function uuid_generate_v4()` comes from the ``uuid-ossp` extension which does exist...

**Comment by enovajuan** [comment]
Refer to this pull for FIX:
https://github.com/enova/landable/pull/49
